name: pr-checks
on: [pull_request]
jobs:
  changeset-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ^6.24.1
          run_install:
            - args: --frozen-lockfile
      - run: git status
      - run: pnpm changeset status --since=main
